---
  title: "TareaR"
  author: "Ricardo morales"
  output:
  html_document:
    mathjax: "http://example.com/MathJax.js"
    self_contained: true
    fig_height: 6
    fig_width: 8
    theme: journal
    highlight: zenburn
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tarea R

### Ejercicio 1
```{r}
Ciudad <- "ambato"
```


### Ejercicio 2
```{r}
paises_cordillera_andes <- c ("Argentina", "Bolivia", "Chile", "Colombia", "Ecuador", "Peru", "Venezuela")

```

### Ejercicio 3
```{r}
Autos_con_los_litros_de_su_motor <- data.frame(identador = seq(1:12),
                                              "Costo_mayor_a_200K_dÓlares" = as.factor(c(rep(0, 10), 1, 1)),
                                              "Autos" = c ("Porsche 991 GT2 RS", "BAC Mono", "Koenigsegg Regera", "Caterham Seven 620R", "SSC Ultimate Aero TT", "Fenyr SuperSport", "Porsche 992 Turbo S", "Bugatti Chiron", "McLaren P1",
                                                          "Aston Martin Valkyrie", "Caparo T1", "Bugatti Veyron Super Sport"),
                                              "Litros_del_motor" = c (3.8, 2.3, 4.3, 2.0, 6.9, 5.1, 3.7, 4.0, 2.6, 2.9, 3.6, 5.0 )) #Litros
Autos_con_los_litros_de_su_motor
```
                                              
### Ejercicio 4
```{r}
data.frame(DNase)
data()
?DNase 
conc <- subset(DNase, conc >= 0.1 & conc <=0.2)
conc
```




